name: kubik-infiniti-production
region: nyc
services:
  - build_command: yarn build:production
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: reflektor-digital-inc/kubik-infiniti-showroom
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: kubik-infiniti-production
    routes:
      - path: /
    run_command: yarn start
